### ISSUE TITLE
Publish for Scala 2.12

### ISSUE THREAD

**Issue by nightscape** [linkedin/isolation-forest#14]
Hi all!

Would it be possible to cross-publish this project to Scala 2.12?
I'm trying to upgrade Microsoft's MMLSpark to Scala 2.12, but I'm currently blocked by isolation-forest having only a 2.11 build.
There seem to be a few options to do this, e.g. https://github.com/prokod/gradle-crossbuild-scala or https://github.com/ADTRAN/gradle-scala-multiversion-plugin

Thanks a lot!

**Comment by jverbus** [comment]
@nightscape, thanks for reaching out!

The automated release library I'm using doesn't current support building and publishing multiple artifacts using different dependencies under the same release version. I filed a request for this a while ago and they are working on it.

https://github.com/mockito/shipkit/issues/858

I can manually build an artifact using 2.12 for the most recent isolation forest version and publish it to Maven Central. This week is pretty packed for me, but I will aim to do this the following week.

**Comment by nightscape** [comment]
In case your interested I could create an SBT build as well, but you're probably more familiar with Gradle and have therefore decided to use it here.

**Comment by jverbus** [comment]
Thanks for the offer, but we use Gradle internally at LinkedIn and would like to stick with it here.

**Comment by jverbus** [comment]
Hey @nightscape, a new artifact built with Scala 2.12 is now available in Maven Central.

https://oss.sonatype.org/#nexus-search;quick~isolation-forest 

```xml
<dependency>
  <groupId>com.linkedin.isolation-forest</groupId>
  <artifactId>isolation-forest_2.4.3_2.12</artifactId>
  <version>0.3.3</version>
</dependency>
```

**Comment by jverbus** [comment]
@nightscape: Please let me know if this works for you. Thanks!

**Comment by nightscape** [comment]
Hey @jverbus, thanks a lot!
It seems that the artifact is currently only in the LinkedIn Nexus repo at
`https://oss.sonatype.org/service/local/repositories/comlinkedin-1736/content/`
Do they maybe have to be [released and promoted](https://help.sonatype.com/repomanager2/staging-releases/managing-staging-repositories#ManagingStagingRepositories-ReleasingaStagingRepository)?

**Comment by jverbus** [comment]
@nightscape: Yep, it needed to be released. It should now be available. Thanks!

**Comment by nightscape** [comment]
I successfully pulled 1.0.0 for Scala 2.12. Thanks a lot!
