### ISSUE TITLE
Publish artifact for spark 3.0.0

### ISSUE THREAD

**Issue by hoffrocket** [linkedin/isolation-forest#22]
Hello,

Would it be possible for you to publish the artifacts compiled against spark 3?

I've built locally and it seems build without any errors using this command line:
`./gradlew test -PsparkVersion=3.0.0 -PscalaVersion=2.12.11`

Although I haven't tested if it works in practice.

**Comment by jverbus** [comment]
@hoffrocket, I created a PR to build and publish artifacts using Spark v3.0.0.

https://github.com/linkedin/isolation-forest/pull/23

It would be good to confirm these artifacts work on a Spark 3 cluster. Have you successfully verified this using the ones you build manually?

Thanks,
James

**Comment by hoffrocket** [comment]
Yes, we're actively fitting a model on Spark 3 without any issues. Thanks!

**Comment by jverbus** [comment]
isolation-forest v1.0.1 artifacts built with Spark 3.0.0 and Scala 2.12.11 are now published to Bintray and Maven Central.
