### ISSUE TITLE
PySpark support

### ISSUE THREAD

**Issue by bgreenwell** [linkedin/isolation-forest#25]
First off, thank you for making this available. I’m wondering if anyone has had success in interfacing with this via Python/pyspark (or sparkR for that matter)? If not, is it possible? Given my limited experience with PySpark, it seems very possible.

**Comment by jverbus** [comment]
This isolation forest library is leveraged by Microsoft's MMLSpark to provide isolation forest functionality in the latter. MMLSpark automatically provides python and R bindings.

You can try it out here: https://github.com/Azure/mmlspark

**Comment by jverbus** [comment]
Closing this. Please let me know if you have success with the MMLSpark recommendation above for python / R bindings.
