### ISSUE TITLE
Multiple Rows as One Data Point

### ISSUE THREAD

**Issue by TAsUjxnMIL** [linkedin/isolation-forest#30]
Hello, 
I have a general question about the Isolation Forest algorithm. 
My dataframe looks like this: 

| | Metric_1 | Metric_2     |
| :---        |    :----:   |          ---: |
| Row_1 |  |   |
| Row_2 | | |

Is it possible that Isolation Forest observes multiple rows as a data instance? That means if Isolation Forest identifies an anomaly, the anomaly shall refer to multiple rows, for example Row_1 and Row_2.
Currently Isolation Forest gives me one row as anomaly but in my data set multiple rows need to be seen as collective and thus only multiple rows can be anomalous. Do you know if there is a solution for this with Isolation Forest or another algorithm?

**Comment by jverbus** [comment]
It sounds like you will need to do some aggregation (e.g., groupby, clustering) before or after you run the isolation forest algorithm. The details of how you choose to do this will be specific to your use case.

**Comment by jverbus** [comment]
I am closing this ticket, because this is not a feature request or issue with the isolation forest library.
