### ISSUE TITLE
Publish for Scala 2.13

### ISSUE THREAD

**Issue by cchantep** [linkedin/isolation-forest#34]
Hi,

Thanks for this library.
Since it's compatible with Spark 3.2, and this Spark version support 2.13, it would be nice to publish the library for this Scala version.

**Comment by jverbus** [comment]
This is done.

https://github.com/linkedin/isolation-forest/pull/37

https://github.com/linkedin/isolation-forest/pull/35

**Comment by jverbus** [comment]
A version with Scala 2.13 and Spark 3.2 is now available in Maven Central.

```
<dependency>
  <groupId>com.linkedin.isolation-forest</groupId>
  <artifactId>isolation-forest_3.2.0_2.13</artifactId>
  <version>3.0.1</version>
</dependency>
```
