### ISSUE TITLE
Installation in spark

### ISSUE THREAD

**Issue by shazriz** [linkedin/isolation-forest#38]
How do we install this library in pyspark? Do you have any guide?

**Comment by wangzhongqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。
王中情：
您好，已收到您的邮件，我会尽快给您回复。谢谢您的邮件！祝您生活愉快！

**Comment by shazriz** [comment]
Oops I don't understand this language above

**Comment by jverbus** [comment]
This library doesn't directly support PySpark.

[Microsoft's SynapseML library](https://github.com/microsoft/SynapseML) leverages our isolation forest implementation and provides a Python API.

https://microsoft.github.io/SynapseML/docs/documentation/estimators/estimators_core/#isolationforest

**Comment by wangzhongqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。
王中情：
您好，已收到您的邮件，我会尽快给您回复。谢谢您的邮件！祝您生活愉快！
