### ISSUE TITLE
Spark 3.4.0 support

### ISSUE THREAD

**Issue by vishalovercome** [linkedin/isolation-forest#41]
I can see that this package only supports upto version 3.2.0 of Spark which is two years old now. Any plans to support newer versions?

**Comment by wangzhongqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。
王中情：
您好，已收到您的邮件，我会尽快给您回复。谢谢您的邮件！祝您生活愉快！

**Comment by jverbus** [comment]
Yes, 3.3.3 and 3.4.1 are now supported.

https://github.com/linkedin/isolation-forest/pull/42
